name: flutter_project_core
description: "Flutter core package made by AXII Software (Ömer Burak Taşkın)"
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"


dependencies:
  flutter:
    sdk: flutter

  #network
  pretty_dio_logger: ^1.4.0
  dio: ^5.9.0

  #local
  shared_preferences: ^2.5.3

  #localization
  intl: ^0.20.2
  flutter_multi_formatter: ^2.13.10


  #ui
  shimmer: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  
  
